In [2]:
# pandas is a library in python used for handling and preparing the data before training the model

import pandas as pd   # here we are creating alias for pandas library which is "pd"

In [3]:
dataset = pd.read_csv("Salary_Data.csv")  #read_csv is a function in pandas used for reading the csv data and return 
                                            # as dataframe and we are storing it in the dataset variable

In [5]:
dataset #print dataset

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [7]:
# now split the input and output assign to independant and dependant variables from the dataset 
# here YearsExperience is the input and Salary is the output
independant = dataset[["YearsExperience"]]  
dependant = dataset[["Salary"]]

In [8]:
independant

    YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [9]:
dependant

      Salary
0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
5    56642.0
6    60150.0
7    54445.0
8    64445.0
9    57189.0
10   63218.0
11   55794.0
12   56957.0
13   57081.0
14   61111.0
15   67938.0
16   66029.0
17   83088.0
18   81363.0
19   93940.0
20   91738.0
21   98273.0
22  101302.0
23  113812.0
24  109431.0
25  105582.0
26  116969.0
27  112635.0
28  122391.0
29  121872.0

In [12]:
# now spilt train dataset and test dataset for this we use sklearn library which has most of the machine learing module, class and functions
# sklear is the library, model_selection is the module 
# here train_test_split splits the dataset into train and test set and returns in the form of  X_train, X_test, y_train, y_test
#X_train = input data for training, X_test = input data for testing, y_train= output data for training, y_test = output data for testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independant,dependant,test_size=0.30,random_state=0)

In [14]:
#LinearRegression is a class create a object "regressor"
#linear_model is a module that has model creations algorithms
#though our output it continuous number / numeric it is regression and we have only one input so its simple Linear Regression
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

In [15]:
#fit function helps model to learn pattern from input data and correct answers in our case (X_train and y_train)
# and give the best values solpe(m) and intercept(b)
regressor.fit(X_train,y_train)

LinearRegression()

In [21]:
#we can acess the bestvalues like below in our case coeficient and intercept
weight = regressor.coef_
weight

array([[9360.26128619]])

In [20]:
bias = regressor.intercept_
bias

array([26777.3913412])

In [23]:
#now our model has the constants already use it to predit using the testset
y_pred = regressor.predict(X_test)

In [26]:
#now need to check if our model is good model or bad one
#for evaluation metrics, the validation parameter we are using is r2 , pass the output testset and predicted output
from sklearn.metrics import r2_score
r_score = r2_score(y_test,y_pred)

In [27]:
r_score

0.9740993407213511

In [28]:
#if r2 score is near 1 then its a good model if its near 0 then its a bad model
#in our case its near 1 so its good model.
#so we gonna save the model and load it for later use

In [31]:
#save the model into sav file
#pickle is a inbuilt python module, pickel save the python object into a file
import pickle
filename = "finalized_model_linear.sav" 
pickle.dump(regressor,open(filename,'wb')) #writing the python object regressor into a file dump() used to write object into binary format into the file